import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faBell,
    faBrain,
    faCalendar,
    faChartBar,
    faChevronDown,
    faChevronUp,
    faCircle,
    faCircleInfo,
    faCircleQuestion,
    faComment,
    faGear,
    faKeyboard,
    faLock,
    faMicrophone,
    faPaperPlane,
    faPlus,
    faRobot,
    faSpinner,
    faSquare,
    faStop,
    faSyncAlt,
    faTimes,
    faUser,
} from '@fortawesome/free-solid-svg-icons';

// Add icons to the library
const solidIcons = [
    faChartBar,
    faBrain,
    faGear,
    faBell,
    faCalendar,
    faUser,
    faLock,
    faCircleQuestion,
    faCircleInfo,
    faChevronDown,
    faChevronUp,
    faCircle,
    faComment,
    faKeyboard,
    faMicrophone,
    faPaperPlane,
    faPlus,
    faRobot,
    faSquare,
    faStop,
    faSpinner,
    faSyncAlt,
    faTimes
];
library.add(solidIcons as any);
